# Adam Martini
# 2-10-13
# Update 1-5-14: added feature scaling and simplified numpy operations to a more efficient
# vectorized implementation

import sys
import csv
import math
import string
import numpy as np

class LogisticRegressionClassifier():
	"""
	This class is responsible for all logistic regression classifier operations.  These operations include
	building a model from training data, class prediction from testing data, and printing the model.
	"""
	def __init__(self, alpha, lmbda):
		self.alpha = float(alpha) # learning rate for gradient ascent
		self.lmbda = float(lmbda) # regularization constant
		self.epsilon = 0.00001 # convergence measure
		self.max_iter = 10000 # the maximum number of iterations through the data before stopping
		self.threshold = 0.5 # the class prediction threshold

	def __str__(self):
		return "<Logistic Regression Classifier Instance: alpha=" + str(self.alpha) + ">\n"

	def fit(self, X, y):
		X_ = self.add_ones(X)
		# create the model from the training data
		self.optimize(X_, y)

	def optimize(self, X, y):
		"""
		This function optimizes the parameters for the logistic regression classification model from training 
		data using learning rate alpha and regularization constant lmbda
		@post: parameter(theta) optimized by gradient descent
		"""
		# initialize optimization arrays
		self.n = X.shape[1] # the number of features
		self.m = X.shape[0] # the number of instances
		self.probas = np.zeros(self.m, dtype='float') # stores probabilities generated by the logistic function
		self.theta = np.zeros(self.n, dtype='float') # stores the model theta

		# iterate through the data at most max_iter times, updating the theta for each feature
		# also stop iterating if error is less than epsilon (convergence tolerance constant)
		print "iter | magnitude of the gradient"
		for iteration in xrange(self.max_iter):
			# calc probabilities
			self.probas = self.get_proba(X)

			# calculate the gradient and update theta
			gw = (1.0/self.m) * np.dot(X.T, (self.probas - y))
			g0 = gw[0] # save the theta_0 gradient calc before regularization
			gw += ((self.lmbda * self.theta) / self.m) # regularize using the lmbda term
			gw[0] = g0 # restore regularization independent theta_0 gradient calc
			self.theta -= self.alpha * gw # update parameters
			
			# calculate the magnitude of the gradient and check for convergence
			loss = np.linalg.norm(gw)
			if self.epsilon > loss:
				break
			
			print iteration, ":", loss

	def get_proba(self, X):
		return 1.0 / (1 + np.exp(- np.dot(X, self.theta)))

	def predict_proba(self, X):
		"""
		Returns the set of classification probabilities based on the model theta.
		@parameters: X - array-like of shape = [n_samples, n_features]
		    		 The input samples.
		@returns: y_pred - list of shape = [n_samples]
				  The probabilities that the class label for each instance is 1 to standard output.
		"""
		X_ = self.add_ones(X)
		return self.get_proba(X_)

	def predict(self, X):
		"""
		Classifies a set of data instances X based on the set of trained feature theta.
		@parameters: X - array-like of shape = [n_samples, n_features]
		    		 The input samples.
		@returns: y_pred - list of shape = [n_samples]
				  The predicted class label for each instance.
		"""
		y_pred = [proba > self.threshold for proba in self.predict_proba(X)]
		return np.array(y_pred)

	def add_ones(self, X):
		# prepend a column of 1's to dataset X to enable theta_0 calculations
		return np.hstack((np.zeros(shape=(X.shape[0],1), dtype='float') + 1, X))

	def print_model(self, features, model_file):
		# wite the parameter values corresponding to each feature to the given model file
		with open(model_file, 'w') as mf:
			for i in xrange(self.n):
				if i == 0:
					mf.write('%f\n' % (self.theta[i]))
				else:
					mf.write('%s %f\n' % (features[i-1], self.theta[i]))


def load_csv(data, features=False):
	"""
	Loads the csv files into numpy arrays.
	@parameters: data The data file in csv format to be loaded
				 features True => the data file includes features as the first row 
	@returns: feature_names - None if features == False, else a list of feature names
			  X - numpy array of data instances with dtype=float
			  y - numpy array of labels
	"""
	print "Loading data from", data

	# first create attribute names tuple and labels array
	if features:
		with open(data, 'rb') as csv_file:
			reader = csv.reader(csv_file)
			feature_names = list(reader.next())
			feature_names.pop() # remove the 'class' feature name
	else:
		feature_names = None

	# load the csv data into a numpy array
	X = np.loadtxt(data, delimiter=",", dtype='float', skiprows=1)
	y = X[:,-1:] # get only the labels
	y = y.flatten() # make the single column 1 dimensional
	y = y.astype(int)
	X = X[:,:-1] # remove the labels column from the data array
	return feature_names, X, y

def scale_features(X):
	# scales all features in dataset X to values between 0.0 and 1.0
	new_min, new_max = 0.0, 1.0
	A_ = X.T
	for i, column in enumerate(A_):
		old_max = column.max()
		old_min = column.min()
		A_[i] = ((column - old_min) / (old_max - old_min + 0.000001) * (new_max - new_min)) + new_min
	X = A_.T

	# vectorized implementation slightly off, still debugging...
	# X_min, X_max = X.min(0), X.max(0)
	# new_min, new_max = 0.0, 1.0
	# X = (((X - X_min) / (X_max - X_min)) * (new_max - new_min)) + new_min

def get_accuracy(y_test, y_pred):
	"""
	@returns: The precision of the classifier, (correct labels / instance count)
	"""
	correct = 0
	for i, pred in enumerate(y_pred):
		if int(pred) == y_test[i]:
			correct += 1
	return float(correct) / y_test.size


def main(train_file, test_file, alpha=0.01, lmbda=0, model_file='model'):
	"""
	Manages files and operations for logistic regression model creation
	"""
	# open and load csv files
	features, X_train, y_train = load_csv(train_file, True)
	dummy, X_test, y_test = load_csv(test_file, True)

	# scale features to encourage gradient descent convergence
	scale_features(X_train)
	scale_features(X_test)

	# create the logistic regression classifier using the training data
	lrc = LogisticRegressionClassifier(alpha, lmbda)
	print "\nCreated a logistic regression classifier =", lrc

	# fit the model to the loaded training data
	print "Fitting the training data...\n"
	lrc.fit(X_train, y_train)

	# predict the results for the test data
	print "Generating probability prediction for the test data...\n"
	y_pred = lrc.predict(X_test)

	### print the classification results ###
	print "The probabilities for each instance in the test set are:\n"
	for prob in lrc.predict_proba(X_test):
		print prob
	# print simple precision metric to the console
	print('Accuracy:  ' + str(get_accuracy(y_test, y_pred)))
	
	# write the model to the model file
	lrc.print_model(features, model_file)


if __name__ == '__main__':
	"""
	The main function is called when logistic.py is run from the command line with filename argumnets
	"""
	args = sys.argv[1:] # Get the filename parameters from the command line
	main( *args )